# Generated by Django 3.2.2 on 2021-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(default='name', max_length=80)),
                ('hostel_address', models.CharField(default='address', max_length=120)),
                ('hostel_state', models.CharField(default='state', max_length=30)),
                ('hostel_city', models.CharField(default='city', max_length=30)),
                ('hostel_rent', models.IntegerField(default='rent')),
                ('hostel_deposit', models.IntegerField(default='deposit')),
                ('hostel_contactnumber', models.IntegerField(default='contact number')),
                ('hostel_pincode', models.IntegerField(default='pincode')),
                ('hostel_area', models.CharField(default='area', max_length=120)),
                ('hostel_mess', models.IntegerField(default='0/1')),
                ('hostel_mealtype', models.CharField(default='mealtype', max_length=120)),
                ('hostel_ac', models.IntegerField(default='0/1')),
                ('hostel_vistorentry', models.IntegerField(default='0/1')),
                ('hostel_watercooler', models.IntegerField(default='0/1')),
                ('hostel_roomcleaning', models.IntegerField(default='0/1')),
            ],
        ),
    ]
