# Generated by Django 3.2.2 on 2021-05-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_hostel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_querry',
            new_name='user_query',
        ),
    ]
