# Generated by Django 3.2.2 on 2021-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210518_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tiffin_service',
            new_name='tiffinservice',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_address',
            new_name='tiffinservice_address',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_area',
            new_name='tiffinservice_area',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_city',
            new_name='tiffinservice_city',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_contactnumber',
            new_name='tiffinservice_contactnumber',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_description',
            new_name='tiffinservice_description',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_image2',
            new_name='tiffinservice_image2',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_images1',
            new_name='tiffinservice_images1',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_mealsperday',
            new_name='tiffinservice_mealsperday',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_mealtype',
            new_name='tiffinservice_mealtype',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_name',
            new_name='tiffinservice_name',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_pincode',
            new_name='tiffinservice_pincode',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_price',
            new_name='tiffinservice_price',
        ),
        migrations.RenameField(
            model_name='tiffinservice',
            old_name='tiffin_service_state',
            new_name='tiffinservice_state',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_ac',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_address',
            field=models.CharField(default='Civil Lines', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_area',
            field=models.CharField(default='Civil Lines', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_pincode',
            field=models.IntegerField(default='110054'),
        ),
    ]
