# Generated by Django 3.2.2 on 2021-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_rename_user_querry_user_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry_name', models.CharField(default='name', max_length=80)),
                ('laundry_address', models.CharField(default='address', max_length=120)),
                ('laundry_state', models.CharField(default='state', max_length=30)),
                ('laundry_city', models.CharField(default='city', max_length=30)),
                ('laundry_price', models.IntegerField(default='0')),
                ('laundry_contactnumber', models.IntegerField(default='+91')),
                ('laundry_pincode', models.IntegerField(default='00')),
                ('laundry_area', models.CharField(default='', max_length=120)),
                ('laundry_description', models.CharField(default='', max_length=120)),
                ('laundry_images1', models.ImageField(default='', upload_to='display/img/laundry_images')),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='name', max_length=80)),
                ('library_address', models.CharField(default='address', max_length=120)),
                ('library_state', models.CharField(default='state', max_length=30)),
                ('library_city', models.CharField(default='city', max_length=30)),
                ('library_deposit', models.IntegerField(default='0')),
                ('library_contactnumber', models.IntegerField(default='+91')),
                ('library_pincode', models.IntegerField(default='00')),
                ('library_area', models.CharField(default='', max_length=120)),
                ('library_description', models.CharField(default='', max_length=120)),
                ('library_images1', models.ImageField(default='', upload_to='display/img/library_images')),
            ],
        ),
        migrations.CreateModel(
            name='tiffin_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffin_service_name', models.CharField(default='name', max_length=80)),
                ('tiffin_service_address', models.CharField(default='address', max_length=120)),
                ('tiffin_service_state', models.CharField(default='state', max_length=30)),
                ('tiffin_service_city', models.CharField(default='city', max_length=30)),
                ('tiffin_service_price', models.IntegerField(default='0')),
                ('tiffin_service_contactnumber', models.IntegerField(default='+91')),
                ('tiffin_service_pincode', models.IntegerField(default='00')),
                ('tiffin_service_area', models.CharField(default='', max_length=120)),
                ('tiffin_service_mealtype', models.CharField(default='veg', max_length=120)),
                ('tiffin_service_mealsperday', models.IntegerField(default=3)),
                ('tiffin_service_description', models.CharField(default='', max_length=120)),
                ('tiffin_service_images1', models.ImageField(default='', upload_to='display/img/tiffin_service_images')),
                ('tiffin_service_image2', models.ImageField(default='', upload_to='display/img/tiffin_service_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='hostel_name',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_image2',
            field=models.ImageField(default='', upload_to='display/img/hostel_images'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_images1',
            field=models.ImageField(default='', upload_to='display/img/hostel_images'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_ac',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_area',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_contactnumber',
            field=models.IntegerField(default='+91'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_deposit',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_mealtype',
            field=models.CharField(default='veg', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_mess',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_pincode',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_rent',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_roomcleaning',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_vistorentry',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_watercooler',
            field=models.IntegerField(default='0'),
        ),
    ]
