# Generated by Django 3.2.2 on 2021-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20210518_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_address',
            field=models.CharField(default='Chandini Chowk', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_area',
            field=models.CharField(default='Chandini Chowk', max_length=120),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_city',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_deposit',
            field=models.IntegerField(default='5000'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_description',
            field=models.TextField(default='veg food allowed, A.C provided, washing machine available, iron availble, Geyser provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_mess',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_pincode',
            field=models.IntegerField(default='110006'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_rent',
            field=models.IntegerField(default='6000'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_roomcleaning',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_state',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_vistorentry',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_watercooler',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_area',
            field=models.CharField(default='Chandini Chowk', max_length=120),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_city',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_pincode',
            field=models.IntegerField(default='110006'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='laundry_state',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_city',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_state',
            field=models.CharField(default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_pincode',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='tiffin_service',
            name='tiffin_service_state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
