# Generated by Django 3.2.6 on 2021-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210807_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_storesservice',
            name='medical_storesservice_price',
        ),
        migrations.AddField(
            model_name='medical_storesservice',
            name='medical_storesservice_timing',
            field=models.CharField(default='', max_length=30),
        ),
    ]
