# Generated by Django 3.2.6 on 2021-08-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20210807_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_mealtype',
            new_name='medical_storesservice_medicinetype',
        ),
        migrations.RemoveField(
            model_name='medical_storesservice',
            name='medical_storesservice_area',
        ),
        migrations.RemoveField(
            model_name='medical_storesservice',
            name='medical_storesservice_mealsperday',
        ),
    ]
