# Generated by Django 3.2.6 on 2021-08-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20210807_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_address',
            new_name='medical_stores_address',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_city',
            new_name='medical_stores_city',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_contactnumber',
            new_name='medical_stores_contactnumber',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_image2',
            new_name='medical_stores_image2',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_images1',
            new_name='medical_stores_images1',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_medicinetype',
            new_name='medical_stores_medicinetype',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_pincode',
            new_name='medical_stores_pincode',
        ),
        migrations.RenameField(
            model_name='medical_storesservice',
            old_name='medical_storesservice_timing',
            new_name='medical_stores_timing',
        ),
    ]
