# Generated by Django 3.2.6 on 2021-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20210807_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(default='', max_length=120)),
                ('laboratory_state', models.CharField(default='Bihar', max_length=30)),
                ('laboratory_city', models.CharField(default='Muzaffarpur', max_length=30)),
                ('laboratory_area', models.CharField(default='Juran Chhapra', max_length=120)),
                ('laboratory_pincode', models.IntegerField(default='110054')),
                ('laboratory_address', models.CharField(default='Muzaffarpur', max_length=120)),
                ('laboratory_contactnumber', models.IntegerField(default='+91')),
                ('laboratory_bloodtest', models.IntegerField(default='1')),
                ('laboratory_ctscan', models.IntegerField(default='1')),
                ('laboratory_rent', models.IntegerField(default='500')),
                ('laboratory_xray', models.IntegerField(default='1')),
                ('laboratory_corona', models.IntegerField(default='1')),
                ('laboratory_description', models.TextField(default='This lab is certified  byCAP (College of American Pathologists) and Certified by ISO 9001 (International Organization of Standardization).', max_length=500)),
                ('laboratory_images1', models.ImageField(default='', upload_to='display/img/laboratory_images')),
                ('laboratory_image2', models.ImageField(default='', upload_to='display/img/laboratory_images')),
            ],
        ),
    ]
