# Generated by Django 3.2.6 on 2021-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_laboratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_name', models.CharField(default='', max_length=120)),
                ('docs_state', models.CharField(default='Delhi', max_length=30)),
                ('docs_city', models.CharField(default='Delhi', max_length=30)),
                ('docs_area', models.CharField(default='Civil Lines', max_length=120)),
                ('docs_pincode', models.IntegerField(default='110054')),
                ('docs_address', models.CharField(default='Civil Lines', max_length=120)),
                ('docs_rent', models.IntegerField(default='6000')),
                ('docs_deposit', models.IntegerField(default='5000')),
                ('docs_contactnumber', models.IntegerField(default='+91')),
                ('docs_mess', models.IntegerField(default='1')),
                ('docs_mealtype', models.CharField(default='veg', max_length=120)),
                ('docs_Physician', models.IntegerField(default='1')),
                ('docs_Dentist', models.IntegerField(default='1')),
                ('docs_Gynaecologist', models.IntegerField(default='1')),
                ('docs_Child', models.IntegerField(default='1')),
                ('docs_Eye', models.IntegerField(default='1')),
                ('docs_Surgeon', models.IntegerField(default='1')),
                ('docs_description', models.TextField(default='veg food allowed, A.C provided, washing machine available, iron availble, Geyser provided', max_length=500)),
                ('docs_images1', models.ImageField(default='', upload_to='display/img/hostel_images')),
                ('docs_image2', models.ImageField(default='', upload_to='display/img/hostel_images')),
            ],
        ),
        migrations.DeleteModel(
            name='hostel',
        ),
    ]
