# Generated by Django 3.2.6 on 2021-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_auto_20210808_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='docs_deposit',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='docs_description',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='docs_image2',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='docs_mealtype',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='docs_mess',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='docs_rent',
        ),
        migrations.AddField(
            model_name='docs',
            name='docs_degree',
            field=models.TextField(default='MBBS M.D, AIMS Delhi', max_length=500),
        ),
        migrations.AddField(
            model_name='docs',
            name='docs_fee',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='docs',
            name='docs_timing',
            field=models.CharField(default='10:00 AM-4:00 PM', max_length=120),
        ),
    ]
